In [192]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [193]:
import pandas as pd


In [194]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Fruits classification/fruit_classification_dataset.csv')
data.head(5)

size (cm)  shape  weight (g)  avg_price (₹)   color  taste     fruit_name
0       25.4  round      3089.2          137.1   green  sweet     watermelon
1       24.6  round      3283.9          163.8   green  sweet     watermelon
2        7.8  round       319.0           91.3   green  sweet  custard apple
3       20.0   oval      1607.0           85.7  orange  sweet         papaya
4       10.2   long       131.5           37.8  yellow  sweet         banana


 1 - Drop the duplicates values

In [195]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

np.int64(0)

2 - Create The X and y


In [196]:
X = data.drop(['fruit_name'], axis=1)
y = data['fruit_name']


*** Split the data into train and test with the methode train_test_split
 ***

In [197]:
from sklearn.model_selection import train_test_split
X_train  , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

Labeled the data using the OneHotEncoding method from scikit learn

In [198]:
from sklearn.preprocessing import OneHotEncoder
encoder_train = OneHotEncoder(handle_unknown='ignore' , sparse_output=False)
encoded_train = encoder_train.fit_transform(X_train[['shape' , 'color' , 'taste']])
name_col = encoder_train.get_feature_names_out(['shape' , 'color' , 'taste'])
new_data = pd.DataFrame(encoded_train , columns=name_col , index=X_train.index)
X_train_encoded = pd.concat([X_train.drop(columns=['shape' , 'color' , 'taste']) , new_data ]  , axis=1)


In [199]:
encoder_test = OneHotEncoder(handle_unknown='ignore' , sparse_output=False)
encoded_test = encoder_test.fit_transform(X_test[['shape' , 'color' , 'taste']])
col_names = encoder_test.get_feature_names_out(['shape' , 'color' , 'taste'])
new_test_data = pd.DataFrame(encoded_test, columns=col_names, index=X_test.index)
X_test_encoded = pd.concat([X_test.drop(columns=['shape','color','taste']), new_test_data], axis=1)


Another way to labled data with another method Label Encoder


In [200]:
from sklearn.preprocessing import  LabelEncoder
label_encoded = LabelEncoder()
y_train = label_encoded.fit_transform(y_train )
y_test = label_encoded.transform(y_test)

**Here we scaled the data using the StandardScaler from scikit learn too**

In [201]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_encoded = scaler.fit_transform(X_train_encoded)
X_test_encoded = scaler.transform(X_test_encoded)

**Now we apply the random forest classifier on the data we prepare**

In [202]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_encoded , y_train)



RandomForestClassifier(random_state=42)

In [203]:
y_pred_train = rf.predict(X_train_encoded)
y_pred_test = rf.predict(X_test_encoded)

In [204]:
from sklearn.metrics import accuracy_score
print(f"The Train Accuracy is {accuracy_score(y_train, y_pred_train)} " )
print(f"The Test Accuracy is {accuracy_score(y_test, y_pred_test)} " )

The Train Accuracy is 1.0 
The Test Accuracy is 1.0 


# Now i will test the model manuel

array([ 0.12873205, -0.29459666,  1.12631964, -0.23488809,  1.08946751,
       -0.98108366, -0.21605573, -0.43091306, -0.51286461, -0.33681119,
       -0.34057261, -0.30497578, -0.49185633,  2.92217724, -0.231835  ,
        0.58608168, -0.50727864])

In [215]:
rf.predict([X_test_encoded[0]])

array([11])

In [208]:
y_test

array([11,  1, 18, ..., 14, 13,  7])

# As you can see the model predict correctly
